<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-05-26T19:02:57Z" name="Suite" finished-at="2019-05-26T19:03:30Z" duration-ms="33246">
    <groups>
    </groups>
    <test started-at="2019-05-26T19:02:57Z" name="EndtoEnd" finished-at="2019-05-26T19:03:15Z" duration-ms="17945">
      <class name="com.friendsurance.tests.EndtoEnd_TC1">
        <test-method signature="endtoEnd_TC1()[pri:0, instance:com.friendsurance.tests.EndtoEnd_TC1@4a003cbe]" started-at="2019-05-26T19:02:57Z" name="endtoEnd_TC1" finished-at="2019-05-26T19:03:13Z" duration-ms="16787" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endtoEnd_TC1 -->
        <test-method is-config="true" signature="quit()[pri:0, instance:com.friendsurance.tests.EndtoEnd_TC1@4a003cbe]" started-at="2019-05-26T19:03:13Z" name="quit" finished-at="2019-05-26T19:03:15Z" duration-ms="1141" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.friendsurance.tests.EndtoEnd_TC1 -->
    </test> <!-- EndtoEnd -->
    <test started-at="2019-05-26T19:03:15Z" name="Functional" finished-at="2019-05-26T19:03:30Z" duration-ms="15263">
      <class name="com.friendsurance.tests.UserChangeCredentials_Test">
        <test-method signature="changePassword()[pri:0, instance:com.friendsurance.tests.UserChangeCredentials_Test@1a245833]" started-at="2019-05-26T19:03:21Z" name="changePassword" finished-at="2019-05-26T19:03:29Z" duration-ms="8128" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changePassword -->
        <test-method is-config="true" signature="quit()[pri:0, instance:com.friendsurance.tests.UserChangeCredentials_Test@1a245833]" started-at="2019-05-26T19:03:29Z" name="quit" finished-at="2019-05-26T19:03:30Z" duration-ms="870" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.friendsurance.tests.UserChangeCredentials_Test -->
      <class name="com.friendsurance.tests.RegisterAsAExistingUser_Test">
        <test-method signature="registerAsAExistingUser()[pri:0, instance:com.friendsurance.tests.RegisterAsAExistingUser_Test@4007f65e]" started-at="2019-05-26T19:03:15Z" name="registerAsAExistingUser" finished-at="2019-05-26T19:03:20Z" duration-ms="5436" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Proper Alert message is not dispalyed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Proper Alert message is not dispalyed
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.assertNotEquals(Assert.java:1157)
at com.friendsurance.tests.RegisterAsAExistingUser_Test.registerAsAExistingUser(RegisterAsAExistingUser_Test.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerAsAExistingUser -->
        <test-method is-config="true" signature="quit()[pri:0, instance:com.friendsurance.tests.RegisterAsAExistingUser_Test@4007f65e]" started-at="2019-05-26T19:03:20Z" name="quit" finished-at="2019-05-26T19:03:21Z" duration-ms="825" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.friendsurance.tests.RegisterAsAExistingUser_Test -->
    </test> <!-- Functional -->
  </suite> <!-- Suite -->
</testng-results>
